### ISSUE TITLE
bashism in makefile

### ISSUE THREAD

**Issue by mrvn** [chambart/ocaml-bytes#2]
The clean target has:

	rm -f bytes.cm{i,o,x,a,xa,xs} bytes.a

This only works with bash, not when /bin/sh is for example dash, like it often is nowadays. If you want to keep using that syntax then the Makefile should set 'SHELL=bash' at the start.

The clean target also leaves other files behind:

    Makefile config.log config.status

**Comment by chambart** [comment]
Thanks for the report. This should be fixed.
